name: Pull Request Review

on: pull_request_target

jobs:
  check_pr:
    name: Check PR
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Comment on PR
        uses: actions/github-script@v3
        if: contains(github.event.action, 'opened')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs = require('fs');
            var data = fs.readFileSync('.github/workflows/template.md', {encoding:'utf8', flag:'r'});
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${data}`
            })
      - name: Label Pull Request
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Finding changed files
        id: files
        uses: lsetiawan/get-changed-files@pr_target
        with:
          format: 'csv'
      - name: Checking files modified
        id: file_check
        run: |
          python .ci_scripts/check-files.py "${{ steps.files.outputs.added_modified }}" ${{ github.event.pull_request.user.login }}
      - name: Success comment
        uses: actions/github-script@v3
        if: success()
        env:
          AUTHOR_NAME: ${{ github.event.pull_request.user.login }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var AUTHOR_NAME = process.env.AUTHOR_NAME;
            var fs = require('fs');
            var data = fs.readFileSync('.github/workflows/template.md', {encoding:'utf8', flag:'r'});
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `âœ… Your changes look great @${AUTHOR_NAME}.`
            })
      - name: Failed comment
        uses: actions/github-script@v3
        if: failure()
        env:
          AUTHOR_NAME: ${{ github.event.pull_request.user.login }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var AUTHOR_NAME = process.env.AUTHOR_NAME;
            var fs = require('fs');
            var data = fs.readFileSync('.github/workflows/template.md', {encoding:'utf8', flag:'r'});
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `ðŸ›‘ Looks like you didn't create changes within the allowed location @${AUTHOR_NAME}.`
            })
      - name: Approve on success.
        id: approve_pr
        uses: hmarr/auto-approve-action@v2
        if: steps.file_check.conclusion == 'success'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto merge.
        uses: "pascalgn/automerge-action@v0.13.1"
        if: steps.approve_pr.conclusion == 'success'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
